In [2]:
%matplotlib inline 
#this line above prepares IPython notebook for working with matplotlib

# See all the "as ..." contructs? They're just aliasing the package names.
# That way we can call methods like plt.plot() instead of matplotlib.pyplot.plot().

import numpy as np # imports a fast numerical programming library
import scipy as sp #imports stats functions, amongst other things
import matplotlib as mpl # this actually imports matplotlib
import matplotlib.cm as cm #allows us easy access to colormaps
import matplotlib.pyplot as plt #sets up plotting under plt
import pandas as pd #lets us handle data as dataframes
#sets up pandas table display
pd.set_option('display.width', 500)
pd.set_option('display.max_columns', 100)
pd.set_option('display.notebook_repr_html', True)

In [6]:
def simulate_prizedoor(number_of_simulation):
    return np.random.randint(0,3,number_of_simulation)

In [7]:
print (simulate_prizedoor(5))

[2 2 2 1 0]


In [8]:
def simulate_guess(nsim):
    return np.zeros(nsim, dtype=np.int)

In [9]:
print(simulate_guess(5))

[0 0 0 0 0]


In [12]:

def goat_door(prizedoors, guesses):
    print(prizedoors, guesses)
    #strategy: generate random answers, and
    #keep updating until they satisfy the rule
    #that they aren't a prizedoor or a guess
    result = np.random.randint(0, 3, prizedoors.size)
    print('Result', result)
    while True:
        bad = (result == prizedoors) | (result == guesses)
        print('Bad', bad)
        if not bad.any():
            print('Bad.any', bad.any())
            return result
        result[bad] = np.random.randint(0, 3, bad.sum())
        print('Final', result[bad])

In [16]:
print(goat_door(simulate_prizedoor(3), simulate_guess(3)))

[1 0 1] [0 0 0]
Result [0 1 0]
Bad [ True False  True]
Final [0 2]
Bad [ True False False]
Final [0]
Bad [ True False False]
Final [1]
Bad [ True False False]
Final [2]
Bad [False False False]
Bad.any False
[2 1 2]
